
//本设置里的参数同时影响天空球和云的Bloom效果
//注意：本设置里的参数调整后不会立刻更新到画面，请使用MME的"全部更新"进行刷新

//----------//

//太阳辉光颜色_低处
float4 SunBloomColorLow = COLOR(255, 136, 23, 255);

//太阳辉光颜色_高处
float4 SunBloomColorHigh = COLOR(140, 132, 95, 255);

//太阳辉光亮度
static const float SunBloomStrenth = 1.5;

//太阳辉光范围
static const float SunBloomPow = 20;

//----------//

//月亮辉光颜色
float4 MoonBloomColor = COLOR(30, 200, 255, 255);

//月亮辉光亮度
static float MoonBloomStrenth = 0.65;

//月亮辉光范围
static float MoonBloomPow = 4.3;

//----------//